version: '3.7'

services: 
  web:
    build: ./
    command: python manage.py runserver 0.0.0.0:5000
    ports: 
      - 5000:5000
    env_file: 
      - ./.env.dev
    depends_on: 
      - db
  db:
    image: "postgres"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=djdocker
      - POSTGRES_PASSWORD=123456a@
      - POSTGRES_DB=django_dev
volumes:
  postgres_data: